### ISSUE TITLE
session can not be shared between proccess

### ISSUE THREAD

**Issue by tianxiaoliang** [rowanmanning/learning-express-cluster#1]
As I see,the express session can not work well in this cluster,right?

**Comment by rowanmanning** [comment]
Half correct, you can use express sessions but you'll need to persist them in a database of some sort. By default it uses an in-memory store (which shouldn't be used in production anyway).

There's a tutorial here which explains how to do this with Redis and MongoDB, though there are adapters for MySQL and other databases http://blog.modulus.io/nodejs-and-express-sessions

Does this solve your problem?
